apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: dXNlcg==  # base64 encoded 'user'
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # base64 encoded 'password'
  POSTGRES_DB: bXlkYXRhYmFzZQ==  # base64 encoded 'mydatabase' 